---
apiVersion: v1
kind: Namespace
metadata:
  name: spacex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spacex
  name: location-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: location-app
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: location-app
    spec:
      containers:
      - image: vindhyadk/location-mysql:main
        imagePullPolicy: Always
        name: location-app
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  namespace: spacex
  name: location-service
spec:
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: location-app
  type: LoadBalancer
status:
  loadBalancer: {}