server:
  port: 9080

spring:
  datasource:
    username: root
    password: abc12345
    url: jdbc:mysql://location.cybdvkyvbis0.us-east-1.rds.amazonaws.com/location
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true